### ISSUE TITLE
Control of plot addition and delete buttons

### ISSUE THREAD

**Issue by grahampullan** [grahampullan/dbslice#18]
Add some flags, e.g.
```
plotRow.noAddPlotButton = true
plot.layout.noDeletePlot = true
```
to help control whether to have buttons to add a plot in a plotRow, or to be able to delete a particular plot.

**Comment by aljazkotnik** [comment]
As you pointed out to me the small multiple plot rows all have a 'ctrl' object, while metadata plot rows do not. I think this is sufficient to decide whether the buttons should be added or not. In the current implementation if the object is present on the plot row object the buttons are not added.

**Comment by aljazkotnik** [comment]
I've added the flags in as:

plotRow      .addPlotButton
plot.layout  .removePlotButton

The flag values can be any 'truthy' or 'falsy' values. If the flags are not specified, the decision falls back on whether plotRow.ctrl exists.

Small multiples are still assumed to not need a remove button.
