### ISSUE TITLE
Collapse plotRow

### ISSUE THREAD

**Issue by grahampullan** [grahampullan/dbslice#29]
Add a button to the plotRow (in plotRowTitle div) that will collapse or expand the plotRowBody div. This would be useful when you want to temporarily hide some plots to keep other plotRows on the screen together.

**Comment by aljazkotnik** [comment]
Hi Graham,
I've added in the functionality to collapse plot rows by clicking on hte plot row header. I've indicated that the plot row can be clicked by applying a css 'hover' effect to the header.
